version: '3.8'

services:
  # PostgreSQL Database for development
  postgres-dev:
    image: postgres:15-alpine
    container_name: hrbooteh-postgres-dev
    environment:
      POSTGRES_DB: hrbooteh_dev
      POSTGRES_USER: hrbooteh_dev
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - hrbooteh-dev-network

  # Redis for development
  redis-dev:
    image: redis:7-alpine
    container_name: hrbooteh-redis-dev
    ports:
      - "6380:6379"
    networks:
      - hrbooteh-dev-network

  # Backend development with hot reload
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder  # Use builder stage for development
    container_name: hrbooteh-backend-dev
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://hrbooteh_dev:dev_password@postgres-dev:5432/hrbooteh_dev
      - REDIS_URL=redis://redis-dev:6379
      - DEBUG=true
    ports:
      - "8001:8000"
    depends_on:
      - postgres-dev
      - redis-dev
    networks:
      - hrbooteh-dev-network
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
    command: python start-dev.py

volumes:
  postgres_dev_data:

networks:
  hrbooteh-dev-network:
    driver: bridge
